"""add date for book

Revision ID: 4d6c0d0f2241
Revises: b30caee3e705
Create Date: 2024-04-12 16:11:05.317281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d6c0d0f2241"
down_revision: Union[str, None] = "b30caee3e705"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("book", sa.Column("publish_date", sa.Date(), nullable=False))
    op.drop_constraint("book_author_id_fkey", "book", type_="foreignkey")
    op.create_foreign_key(
        None, "book", "author", ["author_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "book", type_="foreignkey")
    op.create_foreign_key(
        "book_author_id_fkey", "book", "author", ["author_id"], ["id"]
    )
    op.drop_column("book", "publish_date")
    # ### end Alembic commands ###
