"""unique for author`s last name

Revision ID: 57ba90f3bede
Revises: 4d6c0d0f2241
Create Date: 2024-04-12 16:30:10.610757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "57ba90f3bede"
down_revision: Union[str, None] = "4d6c0d0f2241"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "author", ["last_name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "author", type_="unique")
    # ### end Alembic commands ###
