"""implement unique constraint to DBAuthor model

Revision ID: 8c778033771b
Revises: fe0f28d9ba47
Create Date: 2024-04-15 17:25:29.502367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c778033771b"
down_revision: Union[str, None] = "fe0f28d9ba47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_author_name", "author", ["first_name", "last_name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_author_name", "author", type_="unique")
    # ### end Alembic commands ###
