"""change name 'decription' to 'description'

Revision ID: fe0f28d9ba47
Revises: 57ba90f3bede
Create Date: 2024-04-13 19:34:51.900530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fe0f28d9ba47"
down_revision: Union[str, None] = "57ba90f3bede"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book", sa.Column("description", sa.String(length=512), nullable=False)
    )
    op.drop_column("book", "decription")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book",
        sa.Column(
            "decription",
            sa.VARCHAR(length=512),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("book", "description")
    # ### end Alembic commands ###
